namespace TestTask.Domain.Constants;

public static class Currencies
{
    public static readonly IReadOnlyList<(string Title, string AlphabeticCode, string NumericCode)> Supported = new List<(string, string, string)>()
    {
        ("UAE Dirham", "AED", "784"),
        ("Afghan Afghani", "AFN", "971"),
        ("Albanian Lek", "ALL", "8"),
        ("Armenian Dram", "AMD", "51"),
        ("Netherlands Antillian Guilder", "ANG", "532"),
        ("Angolan Kwanza", "AOA", "973"),
        ("Argentine Peso", "ARS", "32"),
        ("Australian Dollar", "AUD", "36"),
        ("Aruban Florin", "AWG", "533"),
        ("Azerbaijani Manat", "AZN", "944"),
        ("Bosnia and Herzegovina Mark", "BAM", "977"),
        ("Barbados Dollar", "BBD", "52"),
        ("Bangladeshi Taka", "BDT", "50"),
        ("Bulgarian Lev", "BGN", "975"),
        ("Bahraini Dinar", "BHD", "48"),
        ("Burundian Franc", "BIF", "108"),
        ("Bermudian Dollar", "BMD", "60"),
        ("Brunei Dollar", "BND", "96"),
        ("Bolivian Boliviano", "BOB", "68"),
        ("Brazilian Real", "BRL", "986"),
        ("Bahamian Dollar", "BSD", "44"),
        ("Bhutanese Ngultrum", "BTN", "64"),
        ("Botswana Pula", "BWP", "72"),
        ("Belarusian Ruble", "BYN", "933"),
        ("Belize Dollar", "BZD", "84"),
        ("Canadian Dollar", "CAD", "124"),
        ("Congolese Franc", "CDF", "976"),
        ("Swiss Franc", "CHF", "756"),
        ("Chilean Peso", "CLP", "152"),
        ("Chinese Renminbi", "CNY", "156"),
        ("Colombian Peso", "COP", "170"),
        ("Costa Rican Colon", "CRC", "188"),
        ("Cuban Peso", "CUP", "192"),
        ("Cape Verdean Escudo", "CVE", "132"),
        ("Czech Koruna", "CZK", "203"),
        ("Djiboutian Franc", "DJF", "262"),
        ("Danish Krone", "DKK", "208"),
        ("Dominican Peso", "DOP", "214"),
        ("Algerian Dinar", "DZD", "12"),
        ("Egyptian Pound", "EGP", "818"),
        ("Eritrean Nakfa", "ERN", "232"),
        ("Ethiopian Birr", "ETB", "230"),
        ("Euro", "EUR", "978"),
        ("Fiji Dollar", "FJD", "242"),
        ("Falkland Islands Pound", "FKP", "238"),
        ("Faroese Króna", "FOK", "234"),
        ("Pound Sterling", "GBP", "826"),
        ("Georgian Lari", "GEL", "981"),
        ("Guernsey Pound", "GGP", "292"),
        ("Ghanaian Cedi", "GHS", "936"),
        ("Gibraltar Pound", "GIP", "292"),
        ("Gambian Dalasi", "GMD", "270"),
        ("Guinean Franc", "GNF", "324"),
        ("Guatemalan Quetzal", "GTQ", "320"),
        ("Guyanese Dollar", "GYD", "328"),
        ("Hong Kong Dollar", "HKD", "344"),
        ("Honduran Lempira", "HNL", "340"),
        ("Croatian Kuna", "HRK", "191"),
        ("Haitian Gourde", "HTG", "332"),
        ("Hungarian Forint", "HUF", "348"),
        ("Indonesian Rupiah", "IDR", "360"),
        ("Israeli New Shekel", "ILS", "376"),
        ("Manx Pound", "IMP", "833"),
        ("Indian Rupee", "INR", "356"),
        ("Iraqi Dinar", "IQD", "368"),
        ("Iranian Rial", "IRR", "364"),
        ("Icelandic Króna", "ISK", "352"),
        ("Jersey Pound", "JEP", "832"),
        ("Jamaican Dollar", "JMD", "388"),
        ("Jordanian Dinar", "JOD", "400"),
        ("Japanese Yen", "JPY", "392"),
        ("Kenyan Shilling", "KES", "404"),
        ("Kyrgyzstani Som", "KGS", "417"),
        ("Cambodian Riel", "KHR", "116"),
        ("Kiribati Dollar", "KID", "296"),
        ("Comorian Franc", "KMF", "174"),
        ("South Korean Won", "KRW", "410"),
        ("Kuwaiti Dinar", "KWD", "414"),
        ("Cayman Islands Dollar", "KYD", "136"),
        ("Kazakhstani Tenge", "KZT", "398"),
        ("Lao Kip", "LAK", "418"),
        ("Lebanese Pound", "LBP", "422"),
        ("Sri Lanka Rupee", "LKR", "144"),
        ("Liberian Dollar", "LRD", "430"),
        ("Lesotho Loti", "LSL", "426"),
        ("Libyan Dinar", "LYD", "434"),
        ("Moroccan Dirham", "MAD", "504"),
        ("Moldovan Leu", "MDL", "498"),
        ("Malagasy Ariary", "MGA", "969"),
        ("Macedonian Denar", "MKD", "807"),
        ("Burmese Kyat", "MMK", "104"),
        ("Mongolian Tögrög", "MNT", "496"),
        ("Macanese Pataca", "MOP", "446"),
        ("Mauritanian Ouguiya", "MRU", "929"),
        ("Mauritian Rupee", "MUR", "480"),
        ("Maldivian Rufiyaa", "MVR", "462"),
        ("Malawian Kwacha", "MWK", "454"),
        ("Mexican Peso", "MXN", "484"),
        ("Malaysian Ringgit", "MYR", "458"),
        ("Mozambican Metical", "MZN", "943"),
        ("Namibian Dollar", "NAD", "516"),
        ("Nigerian Naira", "NGN", "566"),
        ("Nicaraguan Córdoba", "NIO", "558"),
        ("Norwegian Krone", "NOK", "578"),
        ("Nepalese Rupee", "NPR", "524"),
        ("New Zealand Dollar", "NZD", "554"),
        ("Omani Rial", "OMR", "512"),
        ("Panamanian Balboa", "PAB", "590"),
        ("Peruvian Sol", "PEN", "604"),
        ("Papua New Guinean Kina", "PGK", "598"),
        ("Philippine Peso", "PHP", "608"),
        ("Pakistani Rupee", "PKR", "586"),
        ("Polish Złoty", "PLN", "985"),
        ("Paraguayan Guaraní", "PYG", "600"),
        ("Qatari Riyal", "QAR", "634"),
        ("Romanian Leu", "RON", "946"),
        ("Serbian Dinar", "RSD", "941"),
        ("Russian Ruble", "RUB", "643"),
        ("Rwandan Franc", "RWF", "646"),
        ("Saudi Riyal", "SAR", "682"),
        ("Solomon Islands Dollar", "SBD", "90"),
        ("Seychellois Rupee", "SCR", "690"),
        ("Sudanese Pound", "SDG", "938"),
        ("Swedish Krona", "SEK", "752"),
        ("Singapore Dollar", "SGD", "702"),
        ("Saint Helena Pound", "SHP", "654"),
        ("Sierra Leonean Leone", "SLE", "694"),
        ("Somali Shilling", "SOS", "706"),
        ("Surinamese Dollar", "SRD", "968"),
        ("South Sudanese Pound", "SSP", "728"),
        ("São Tomé and Príncipe Dobra", "STN", "930"),
        ("Syrian Pound", "SYP", "760"),
        ("Eswatini Lilangeni", "SZL", "748"),
        ("Thai Baht", "THB", "764"),
        ("Tajikistani Somoni", "TJS", "972"),
        ("Turkmenistan Manat", "TMT", "934"),
        ("Tunisian Dinar", "TND", "788"),
        ("Tongan Paʻanga", "TOP", "776"),
        ("Turkish Lira", "TRY", "949"),
        ("Trinidad and Tobago Dollar", "TTD", "780"),
        ("Tuvaluan Dollar", "TVD", "548"),
        ("New Taiwan Dollar", "TWD", "901"),
        ("Tanzanian Shilling", "TZS", "834"),
        ("Ukrainian Hryvnia", "UAH", "980"),
        ("Ugandan Shilling", "UGX", "800"),
        ("United States Dollar", "USD", "840"),
        ("Uruguayan Peso", "UYU", "858"),
        ("Uzbekistani So'm", "UZS", "860"),
        ("Venezuelan Bolívar Soberano", "VES", "928"),
        ("Vietnamese Đồng", "VND", "704"),
        ("Vanuatu Vatu", "VUV", "548"),
        ("Samoan Tālā", "WST", "882"),
        ("Central African CFA Franc", "XAF", "950"),
        ("East Caribbean Dollar", "XCD", "951"),
        ("Special Drawing Rights", "XDR", "960"),
        ("West African CFA franc", "XOF", "952"),
        ("CFP Franc", "XPF", "953"),
        ("Yemeni Rial", "YER", "886"),
        ("South African Rand", "ZAR", "710"),
        ("Zambian Kwacha", "ZMW", "967"),
        ("Zimbabwean Dollar", "ZWL", "932"),
    };
}